import type { ReactNode } from 'react';

import type { Metadata } from 'next';
import { Anton } from 'next/font/google';
import Link from 'next/link';

import { ThemeProvider } from 'next-themes';

import '@/app/globals.css';

const anton = Anton({
    weight: '400',
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        // ? https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
        // ? https://react.dev/reference/react-dom/client/hydrateRoot#suppressing-unavoidable-hydration-mismatch-errors

        <>
            <header className='fixed top-[var(--header-spacing-top)] left-1/2 z-10 -translate-x-1/2'>
                <div className='light:bg-stone-200 flex h-[var(--header-height)] min-w-md items-center justify-between gap-4 rounded-2xl bg-zinc-900 px-8'>
                    <Link href='/'>
                        <Logo />
                    </Link>
                    <button className='text-sm font-medium'>Menu</button>
                </div>
            </header>
            <main className='main min-h-screen'>{children}</main>
        </>
    );
};

export default Layout;

const Logo = () => {
    return <div className='text-xl font-bold'>Logo</div>;
};
