import type { ReactNode } from 'react';

import type { Metadata } from 'next';
import { Anton } from 'next/font/google';

import { ThemeProvider } from 'next-themes';

import '@/app/globals.css';

const anton = Anton({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-anton'
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        // ? https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
        // ? https://react.dev/reference/react-dom/client/hydrateRoot#suppressing-unavoidable-hydration-mismatch-errors
        <html suppressHydrationWarning lang='en'>
            <body className={`${anton.variable} bg-background text-foreground antialiased`}>
                <ThemeProvider attribute='class' defaultTheme='dark'>
                    <div className='main min-h-screen'>{children}</div>
                </ThemeProvider>
            </body>
        </html>
    );
};

export default Layout;
